version: "3"

services:
  load_balancer:
    image: "nginx"
    depends_on:
      - "wordpress1"
      - "wordpress2"
      - "wordpress3"
    ports:
      - "80:80"
    volumes:
      - /home/augusto/Área de Trabalho/Sistemas Distribuidos/config/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/html:/usr/share/nginx/html

  database:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - /var/www/html:/var/www/html
    env_file:
      - ./env/database.env
      

  
  wordpress1:
    depends_on:
      - "database"
    image: wordpress
    volumes:
      - /var/www/html:/var/www/html
    env_file:
      - ./env/wordpress.env
      
  wordpress2:
    depends_on:
      - "database"
    image: wordpress
    volumes:
      - /var/www/html:/var/www/html
    env_file:
      - ./env/wordpress.env

  wordpress3:
    depends_on:
      - "database"
    image: wordpress
    volumes:
      - /var/www/html:/var/www/html
    env_file:
      - ./env/wordpress.env      
  
 